name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'modulos/**'

  # Habilita o gatilho manual através da interface do Github Actions
  workflow_dispatch:

jobs:
  # Job para a execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração de passos do job
    steps:
      # 1. Check-out do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Definir permissões de execução para o script gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      # 4. Executar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test